
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - rollup.config.js
  - node_modules
  - netlify.toml

source: src
destination: dist

sass:
  style: compressed

# seo information
author: Christopher Voigt
title: the News
description: A simple news page for my talk at MobileCamp '19

# manifest information
manifest:
  name: the News
  short_name: News
  display: standalone

github:
  username: chlorophyllkid
  repository_name: pwa-example

netlify:
  project_name: chlorophyllkid-pwa-example
