
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# seo information
author: Christopher Voigt
title: Progressive Weather App
description: A progressive web app that takes away the work to look out of the window!

# manifest information
short_name: Weather

# social media
github_username: chlorophyllkid
twitter_username: chlorophyllkid
