
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - rollup.config.js
  - node_modules

sass:
  style: compressed

# seo information
author: Christopher Voigt
title: PWA Example
description: A simple blog page for my talk at MobileCamp '19

# manifest information
manifest:
  name: PWA Example
  short_name: Example
  display: standalone

github:
  username: chlorophyllkid
  repository_name: pwa-example

netlify:
  project_name: chlorophyllkid-pwa-example
